# Generated by Django 4.2.1 on 2023-05-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
